### ISSUE TITLE
Does the perl run dep need to be so exact?

### ISSUE THREAD

**Issue by scopatz** [conda-forge/imagemagick-feedstock#12]
I noticed it was conflicting with some other packages (namely `latexmk`) which did not pin perl to a specific version.  I ended up with the following error:

```console
scopatz@artemis ~ $ conda install latexmk
Fetching package metadata .............
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
  - imagemagick -> perl 5.22.2.1
  - latexmk -> perl 5.20.3*
Use "conda info <package>" to see the dependencies for each package.
```

Also not sure why latexmk seemed to be pinned to 5.20.3*, when the recipe has no pin, [as seen here](https://github.com/conda-forge/latexmk-feedstock/blob/master/recipe/meta.yaml#L21).

**Comment by ocefpaf** [comment]
Probably not. The build one is to avoid a build matrix. Do you mind sending a PR?

**Comment by ocefpaf** [comment]
I guess that changing to the new pinning format this was done automatically.
