### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by ahartikainen** [conda-forge/imagemagick-feedstock#13]
Hi,  

is there some reason there is no windows version build?

If there are some compilation problems, where can I found some information concerning it?

**Comment by ocefpaf** [comment]
> is there some reason there is no windows version build?

I don't know where to start. If you have any Windows expertise please a PR is very welcomed :smile:

Closing this b/c it is not an actionable issue for the active maintainers of this feedstock.

**Comment by ahartikainen** [comment]
Thanks for the info. I will see if I can help.
