### ISSUE TITLE
Not bot compliant

### ISSUE THREAD

**Issue by justcalamari** [conda-forge/imagemagick-feedstock#14]
The recipe has `{% set version = "7.0.7" %}` and 
`url: https://github.com/ImageMagick/ImageMagick/archive/{{ version }}-11.tar.gz`.
The bot wants to update the version to 7.0.8-0, making the url `https://github.com/ImageMagick/ImageMagick/archive/7.0.8-0-11.tar.gz` when it should be `https://github.com/ImageMagick/ImageMagick/archive/7.0.8-0.tar.gz`
@ocefpaf

**Comment by ocefpaf** [comment]
Oh the irony! Getting hit by the policy I just supported :smile: 

I'll fix that ASAP.
