### ISSUE TITLE
Relaxing pinned dependency versions

### ISSUE THREAD

**Issue by dhimmel** [conda-forge/imagemagick-feedstock#7]
Currently, the `build` and `run` dependencies in `meta.yaml` are quite specific:

This led to problems in https://github.com/conda-forge/staged-recipes/pull/4613, where the builds didn't use the latest imagemagick version. @jdblischak [diagnosed](https://github.com/conda-forge/staged-recipes/pull/4613#issuecomment-352593515) the issue as:

> I think the problem is conflicting dependencies between r-base and imagemagick. r-base 3.3.2_5 requires zlib 1.2.8. The most recent imagemagick that is pinned with zlib 1.2.8 is imagemagick-7.0.6-pl5.22.2.1_0, which is why it is getting selected. libpng may also be a problem.

Here are the current `run` dependencies:

https://github.com/conda-forge/imagemagick-feedstock/blob/a3effa0d28aa14cd9b000c6cbffe4d85d5c2dd20/recipe/meta.yaml#L39-L61

@ocefpaf how do you determine whether a certain dependency should be versioned? Should run and build versions always be the same? Can we relax some of the run dependencies to enable compatibility with more conda environments?

**Comment by bgruening** [comment]
Also see: https://github.com/conda-forge/r-base-feedstock/pull/27

**Comment by jdblischak** [comment]
@dhimmel The strict pins are critical for interoperability of conda-forge packages:

https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies

Thus there are two options (not mutually exclusive):

1. Update the pins for r-base (a work in progress as noted by @bgruening)
2. Update the recipe for an older version of imagemagick (which has the old pinned versions) to enable magick

**Comment by ocefpaf** [comment]
@jdblischak you are 100% correct. But things should be better once we move to conda-build 3 b/c it carries the info of the packages used at build time reducing those incompatibilities.

**Comment by jdblischak** [comment]
>  once we move to conda-build 3

@ocefpaf Is there a central Issue open somewhere where progress on migration to conda-build 3 is being tracked?

**Comment by ocefpaf** [comment]
There was a "mega thread" but I do not recommend going there. We will create a better one soon, right now the DBox paper minutes of the meetings are the best place to get some info of the state of things.

https://paper.dropbox.com/doc/Compiler-meeting-20171116-1lYaDIP93JRzzQZBlicxg

and 

https://paper.dropbox.com/doc/Compilers-conda-build-3-update-20171211-JSvRO2Lk2Z7Bbf2zDaG9p

**Comment by dhimmel** [comment]
To make sure I understand, if a program depends on a program that's listed in [`pin_the_slow_way.py`](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py), then it must be pinned. Otherwise, dependencies should be pinned only based on the requirements of the package being installed. When `pin_the_slow_way.py` is updated it creates a rift, where packages on either side are not interoperable (the issue above).

**Comment by ocefpaf** [comment]
> To make sure I understand, if a program depends on a program that's listed in pin_the_slow_way.py, then it must be pinned.

Correct.

> Otherwise, dependencies should be pinned only based on the requirements of the package being installed

Actually, the requirements comes first and, when inconsistent with `pin_the_slow_way`, we should fix `pin_the_slow_way` or open an exception to it.

> When pin_the_slow_way.py is updated it creates a rift, where packages on either side are not interoperable (the issue above).

We had a bot to update the pinning but was problematic. Now we are moving towards conda-build 3 to solve that. Note that conda-build 3 won't make things magically work, but will prevent the user from installing incompatible set of packages. We will still need to re-build stuff to get the latest dependencies.
