### ISSUE TITLE
PNG Plugin working?

### ISSUE THREAD

**Issue by kyleabeauchamp** [conda-forge/imagemagick-feedstock#8]
Has anyone observed any issues with the PNG plugin?  I'm getting an exception that suggests issues with the plugin:

```
$ magick montage  -geometry +4+4  in.png in.png in.png in.png out.png
montage: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.
montage:  `out.png' @ error/montage.c/MontageImageCommand/1775.
```

As far as I can tell, I have the necessary conda packages installed:

```
$ conda list libpng
libpng                    1.6.34                        0    conda-forge
$ conda list imagemagick
imagemagick               7.0.7              pl5.22.2.1_2    conda-forge
```

I wonder if there is something fishy going on with the shared object files / linking that occurs at run time.  I glanced at the debug logs but didn't see anything there.

**Comment by kyleabeauchamp** [comment]
PS: I'm on OSX 10.13.2, using the latest miniconda3 (in a py36 environment with numpy + matplotlib, FWIW).

**Comment by kyleabeauchamp** [comment]
FWIW, I removed the conda version and used brew with success, so I *strongly* suspect something in the conda package.

**Comment by ocefpaf** [comment]
Worked for me but I'm on Linux, I cannot test this on OS X but I did test it on the CIs and it worked too, here are my versions:

```
libpng                    1.6.34                        0    conda-forge
imagemagick               7.0.8_0                 pl522_0    conda-forge
```

Please take a look at https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels and check if you are not mixing channels.

**Comment by matheboy** [comment]
@ocefpaf I check my channels and they are as recommended. 
I am on miniconda2, I installed imagemagick on the root env ( I need it so ) and I have the same issue as @kyleabeauchamp.

**Comment by ocefpaf** [comment]
@matheboy I don't have a Mac to test it and things do work on Linux for me :-/

Can you send the results of your `conda list` for the env where you installed `imagemagick`? I'll add a test here in the feedstock to see if that command passes on Travis-CI.

**Comment by matheboy** [comment]
@ocefpaf here is the output of conda list (I hope it helps):

`
 Name                    Version                   Build  Channel
--------------------------------------------------------------
altgraph                  0.15                      <pip>
asn1crypto                0.24.0                   py27_0    conda-forge
astroid                   1.6.3                    py27_0    conda-forge
autoconf                  2.69               pl5.22.2.1_5    conda-forge
automake                  1.15.1             pl5.22.2.1_0    conda-forge
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.5                      py27_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cffi                      1.9.1                     <pip>
cffi                      1.11.5                   py27_0    conda-forge
chardet                   3.0.4                    py27_0    conda-forge
cherrypy-wsgiserver       0.1.dev0                  <pip>
cmake                     3.9.6                         1    conda-forge
conda                     4.5.4                    py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configparser              3.5.0                    py27_0    conda-forge
cryptography              2.2.1                    py27_0    conda-forge
curl                      7.59.0                        1    conda-forge
dis3                      0.1.2                     <pip>
Django                    1.11                      <pip>
django-cherrypy           0.2                       <pip>
djangorestframework       3.8.2                     <pip>
enum34                    1.1.6                    py27_1    conda-forge
expat                     2.2.5                         0    conda-forge
fftw                      3.3.7                         0    conda-forge
fixerio                   0.1.1                     <pip>
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
future                    0.16.0                    <pip>
futures                   3.2.0                    py27_0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
ghostscript               9.22                          0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
graphite2                 1.3.11               h7d4d677_0    conda-forge
graphviz                  2.38.0                        7    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py27_1    conda-forge
imagemagick               7.0.8_2                 pl522_0    conda-forge
ipaddress                 1.0.18                   py27_0    conda-forge
isort                     4.3.4                    py27_0    conda-forge
jbig                      2.1                           0    conda-forge
jpeg                      9b                            2    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1                    py27_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgit2                   0.27.0                        0    conda-forge
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libssh2                   1.8.0                         2    conda-forge
libtiff                   4.0.9                he6b73bb_0    conda-forge
libuuid                   1.0.3                         1    conda-forge
libuv                     1.20.3                        0    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
m4                        1.4.18                        0    conda-forge
macholib                  1.9                       <pip>
mccabe                    0.6.1                    py27_0    conda-forge
mercurial                 4.5                      py27_0    conda-forge
ncurses                   5.9                          10    conda-forge
openjpeg                  2.3.0                         2    conda-forge
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pango                     1.40.14                       0    conda-forge
pcre                      8.41                          1    conda-forge
pefile                    2017.11.5                 <pip>
perl                      5.22.2.1                      0    conda-forge
pip                       9.0.3                    py27_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pycosat                   0.6.3                    py27_0    conda-forge
pycparser                 2.18                     py27_0    conda-forge
pygit2                    0.25.1                    <pip>
pygit2                    0.27.0                   py27_0    conda-forge
PyInstaller               3.3.1                     <pip>
pylint                    1.8.4                    py27_0    conda-forge
pyopenssl                 17.5.0                   py27_1    conda-forge
pyparsing                 2.2.0                    py27_0    conda-forge
pyside2                   5.6.0a1                  py27_0    conda-forge
pysocks                   1.6.8                    py27_1    conda-forge
python                    2.7.14                        5    conda-forge
python.app                1.2                      py27_0    conda-forge
pytz                      2018.3                    <pip>
qt                        5.6.2                h9e3eb04_4    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.10.0                    <pip>
requests                  2.18.4                   py27_1    conda-forge
rhash                     1.3.4                         0    conda-forge
ruamel_yaml               0.15.35                  py27_0    conda-forge
setuptools                38.5.2                    <pip>
setuptools                39.0.1                   py27_0    conda-forge
shiboken                  1.1.2                    py27_0  
singledispatch            3.4.0.3                  py27_0    conda-forge
six                       1.11.0                   py27_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
urllib3                   1.22                     py27_0    conda-forge
virtualenv                15.1.0                   py27_0    conda-forge
wheel                     0.31.0                   py27_0    conda-forge
wrapt                     1.10.11                  py27_0    conda-forge
xorg-kbproto              1.0.7                         1    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.5                         0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-libxt                1.1.5                         0    conda-forge
xorg-renderproto          0.11.1                        1    conda-forge
xorg-xextproto            7.3.0                         1    conda-forge
xorg-xproto               7.0.31                        6    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zc.buildout               2.10.0                    <pip>
zlib                      1.2.11                        0    conda-forge
`

**Comment by jbloom** [comment]
I get the same error described here by others:
```
$ convert temp.pdf temp.png
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/512.
convert: no images defined `temp.png' @ error/convert.c/ConvertImageCommand/3275.
```

I get this error on Mac OS X (10.12.6). It works fine on Linux.

Here is the result of `conda list`:
```
conda list "libpng|imagemagick"
#
# Name                    Version                   Build  Channel
imagemagick               7.0.8_7         pl526h734ff71_1    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
```

**Comment by telatin** [comment]
I have the same problem with **macos 10.15.3**:
```
conda list "libpng|imagemagick"
# packages in environment at /Users/telatina/miniconda3:
#
# Name                    Version                   Build  Channel
imagemagick               7.0.8_7         pl522h734ff71_0    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
```

**Comment by azeeka** [comment]
Running 
```
convert -list configure
``` 
on macOS 11 (M1) returns

![image](https://user-images.githubusercontent.com/17175112/141337715-9c3712dc-ba48-4307-818f-382659b99685.png)

Is it possible to enable the png flag? It seems that the build machine does not have libpng installed or the flag is just disabled

**Comment by chazeon** [comment]
I think this still has not been fixed.
